version: '3'
services:
  app:
    image: python:3.11
    container_name: python-app
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      /bin/bash -c "pip install -r requirements.txt && python main.py"
    ports:
      - "5000:5000" 
      - "3000:3000" 
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/messages_db

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
